### ISSUE TITLE
 Error loading types from assembly CC_RemoteTech, Version=0.5.5.0

### ISSUE THREAD

**Issue by t0chas** [jrossignol/ContractPack-RemoteTech#4]
Hi I updated RemoteTech to v1.6.1 and got this error message
my active contracts went away and also my contract archive

https://github.com/RemoteTechnologiesGroup/RemoteTech/releases/tag/v1.6.1

full log at https://dl.dropboxusercontent.com/u/72963294/KSPPlugins/ContractConfigurator/CC_RemoteTech/output_log_rt1.6.1.txt

```
[INFO] ContractConfigurator.LoggingUtil: Loading DebuggingConfig node.

(Filename: C:/BuildAgent/work/d63dfc6385190b60/artifacts/StandalonePlayerGenerated/UnityEngineDebug.cpp Line: 49)

[WARNING] Error loading types from assembly CC_RemoteTech, Version=0.5.5.0, Culture=neutral, PublicKeyToken=null: The classes in the module cannot be loaded.
```

**Comment by jrossignol** [comment]
Thanks for the bug report, I literally fixed this within the last hour - grab [ContractConfigurator 0.5.8](https://github.com/jrossignol/ContractConfigurator/releases/tag/0.5.8)...  which will also prevent the entire contract archive from getting blown away next time (although there hopefully isn't a next time for this kind of issue).
